import 'dart:io';

import 'package:args/command_runner.dart';
import 'package:gexd/gexd.dart';
import 'package:mason_logger/mason_logger.dart';
import 'package:path/path.dart' as path;
import 'package:yaml/yaml.dart';

/// Command to display current project configuration
class ConfigCommand extends Command<int> with HasProjectData {
  final Logger _logger;

  ConfigCommand({Logger? logger}) : _logger = logger ?? Logger();

  @override
  String get name => 'config';

  @override
  String get description => 'Show current project configuration';

  @override
  String get usage =>
      '''
$description

Usage: $invocation

Displays information about the current Gexd project including:
- Project name and template type
- Creation and update dates  
- Gexd version information
- Project location

Examples:
  gexd info config                    # Show project configuration
''';

  @override
  Future<int> run() async {
    try {
      // Check if we're in a valid Gexd project
      final projectTemplate = await this.projectTemplate;
      if (projectTemplate == null) {
        _logger.err('❌ Not inside a valid Gexd project.');
        _logger.info(
          '💡 Run this command from within a Gexd-generated project directory.',
        );
        return ExitCode.config.code;
      }

      // Read project configuration
      final configPath = path.join(
        Directory.current.path,
        '.gexd',
        'config.yaml',
      );
      final configFile = File(configPath);

      if (!await configFile.exists()) {
        _logger.err('❌ Project configuration file not found.');
        _logger.info(
          '💡 The .gexd/config.yaml file may be missing or corrupted.',
        );
        return ExitCode.config.code;
      }

      final configContent = await configFile.readAsString();
      final yamlData = loadYaml(configContent);
      final configData = Map<String, dynamic>.from(yamlData as Map);

      // Display project information
      _displayProjectInfo(configData, projectTemplate);

      return ExitCode.success.code;
    } catch (error) {
      _logger.err('❌ Error reading project configuration: $error');
      return ExitCode.software.code;
    }
  }

  void _displayProjectInfo(
    Map<String, dynamic> config,
    ProjectTemplate template,
  ) {
    final currentDir = Directory.current.path;
    final projectName = config['project_name'] ?? 'Unknown';
    final templateName = config['template'] ?? 'Unknown';
    final generatedBy = config['generated_by'] ?? 'Gexd CLI';
    final creationVersion = config['creation_version'] ?? 'Unknown';
    final currentVersion = config['current_version'] ?? 'Unknown';
    final generatedDate = config['generated_date'] ?? 'Unknown';
    final lastUpdated = config['last_updated'] ?? 'Never';

    _logger.info('');
    _logger.info('📄 ${lightCyan.wrap('Project Configuration')}');
    _logger.info('━━━━━━━━━━━━━━━━━━━━━━━━━');
    _logger.info('');

    // Project details
    _logger.info(
      '${lightBlue.wrap('🏗️  Template:')} ${green.wrap(templateName)}',
    );
    _logger.info(
      '${lightBlue.wrap('📝  Project:')} ${white.wrap(projectName)}',
    );
    _logger.info(
      '${lightBlue.wrap('📍  Location:')} ${darkGray.wrap(currentDir)}',
    );
    _logger.info('');

    // Generation details
    _logger.info(
      '${lightBlue.wrap('⚙️  Generated By:')} ${white.wrap(generatedBy)}',
    );
    _logger.info(
      '${lightBlue.wrap('📦  Creation Version:')} ${white.wrap(creationVersion)}',
    );
    _logger.info(
      '${lightBlue.wrap('🔄  Current Version:')} ${white.wrap(currentVersion)}',
    );
    _logger.info('');

    // Dates
    _logger.info(
      '${lightBlue.wrap('🕒  Created:')} ${white.wrap(generatedDate)}',
    );
    _logger.info(
      '${lightBlue.wrap('📅  Last Updated:')} ${_formatLastUpdated(lastUpdated)}',
    );
    _logger.info('');

    // Template description
    _displayTemplateInfo(template);
  }

  void _displayTemplateInfo(ProjectTemplate template) {
    final templateInfo = _getTemplateInfo(template);

    _logger.info('${lightCyan.wrap('📖 Template Information')}');
    _logger.info('━━━━━━━━━━━━━━━━━━━━━━━━━');
    _logger.info(
      '${lightBlue.wrap('Description:')} ${white.wrap(templateInfo['description']!)}',
    );
    _logger.info(
      '${lightBlue.wrap('Best For:')} ${white.wrap(templateInfo['bestFor']!)}',
    );
    _logger.info(
      '${lightBlue.wrap('Features:')} ${white.wrap(templateInfo['features']!)}',
    );
    _logger.info('');

    _logger.info(
      '💡 ${darkGray.wrap('Run')} ${yellow.wrap('gexd info template ${template.key} --full')} ${darkGray.wrap('to see the complete directory structure.')}',
    );
  }

  Map<String, String> _getTemplateInfo(ProjectTemplate template) {
    switch (template) {
      case ProjectTemplate.getx:
        return {
          'description':
              'GetX modular architecture with feature-based organization',
          'bestFor': 'Rapid development, medium-sized apps, GetX enthusiasts',
          'features':
              'Reactive state management, dependency injection, routing',
        };
      case ProjectTemplate.clean:
        return {
          'description':
              'Clean Architecture with domain-driven design principles',
          'bestFor':
              'Enterprise applications, complex business logic, scalable architecture',
          'features': 'Layered architecture, dependency inversion, testability',
        };
    }
  }

  String _formatLastUpdated(dynamic lastUpdated) {
    if (lastUpdated == null ||
        lastUpdated == 'Never' ||
        lastUpdated.toString().isEmpty) {
      return darkGray.wrap('Never') ?? 'Never';
    }
    return white.wrap(lastUpdated.toString()) ?? lastUpdated.toString();
  }
}
