// lib/src/templates/component_metadata.dart
import 'package:gexd/src/core/enums/project_template.dart';
import 'package:meta/meta.dart';

/// Metadata for a single component (e.g. routes, core, models).
///
/// - `supportedTemplates` specifies which templates support this component (GetX, Clean, ...).
/// - `defaultPath` maps each template to the default folder path within the generated project.
/// - `isEssential` determines if the component is essential for the template (generated by default).
@immutable
class ComponentMetadata {
  /// Component description (for display in CLI or documentation).
  final String description;

  /// Component category (core, data, presentation, navigation, ui, ...).
  final String category;

  /// Set of supported templates for this component (ProjectTemplate enum).
  final Set<ProjectTemplate> supportedTemplates;

  /// Map that links a template to the component's default path.
  /// Example: { ProjectTemplate.getx: 'lib/app/core' }
  final Map<ProjectTemplate, String> defaultPath;

  /// Map that determines if the component is essential for each template (true/false).
  final Map<ProjectTemplate, bool> isEssential;

  // const ComponentMetadata({
  //   required this.description,
  //   required this.category,
  //   required Set<ProjectTemplate> supportedTemplates,
  //   Map<ProjectTemplate, String>? defaultPath,
  //   Map<ProjectTemplate, bool>? isEssential,
  // }) : supportedTemplates = supportedTemplates,
  //      defaultPath = defaultPath ?? const {},
  //      isEssential = isEssential ?? const {};

  const ComponentMetadata({
    required this.description,
    required this.category,
    required this.supportedTemplates,
    Map<ProjectTemplate, String>? defaultPath,
    Map<ProjectTemplate, bool>? isEssential,
  }) : defaultPath = defaultPath ?? const {},
       isEssential = isEssential ?? const {};

  /// Does this component support the given template?
  bool supports(ProjectTemplate tpl) => supportedTemplates.contains(tpl);

  /// Is this component essential for the given template?
  bool essentialFor(ProjectTemplate tpl) => isEssential[tpl] ?? false;

  /// Default path for this component for the given template (or null if not available).
  String? pathFor(ProjectTemplate tpl) => defaultPath[tpl];

  /// Display supported template keys as text (useful for printing).
  List<String> supportedTemplateKeys() =>
      supportedTemplates.map((t) => t.key).toList();

  @override
  String toString() {
    return 'ComponentMetadata(description: $description, category: $category, supportedTemplates: ${supportedTemplateKeys().join(",")})';
  }
}
