// ignore_for_file: prefer_const_constructors

import 'package:flutter/material.dart';
import 'package:get/get.dart';

import 'package:{{project_name.snakeCase()}}/app/core/bindings/initial_binding.dart';
import 'package:{{project_name.snakeCase()}}/app/core/themes/app_theme.dart';
import 'package:{{project_name.snakeCase()}}/app/routes/app_pages.dart';

/// {{project_name}} — Main entry point
///
/// Responsibilities:
/// - Registers global dependencies via `InitialBinding`
/// - Provides light/dark themes from `AppTheme`
/// - Configures navigation using `AppPages`
///
/// Generated by Gexd CLI ({{template.pascalCase()}})
void main() {
  runApp(const MainApp());
}

/// Main Application Widget
class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      title: '{{project_name}}',

      // Theme configuration
      theme: AppTheme.lightTheme,
      darkTheme: AppTheme.darkTheme,
      themeMode: ThemeMode.system,

      // Navigation configuration
      initialRoute: AppPages.INITIAL,
      getPages: AppPages.routes,
      unknownRoute: AppPages.UNKNOWN,

      // Global bindings
      initialBinding: InitialBinding(),

      // App configuration
      debugShowCheckedModeBanner: false,
      enableLog: true,

      // Localization (uncomment if needed)
      // locale: const Locale('en', 'US'),
      // translations: AppTranslations(),

      // Global middlewares
      routingCallback: (routing) {
        // Add global route logging or analytics here
        debugPrint('[Navigation] ${routing?.current}');
      },
    );
  }
}
